### ISSUE TITLE
Filtering and sorting for Training Module intents

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#640]
AS A Chatbot Trainer
I WANT TO be able to filter and sort the list of intents
SO THAT I can change the order of intents and filter out common intents

Currently the list of intents is displayed in alphabetical order with intents created by users and common intents mixed together. The default list should always display common intents at the bottom, separated from user intents by a line. It should be possible to order the list either alphabetically, by last modified date or by whether the intent is in model. It should also be possible to filter out common intents so that only intents created by users are displayed.

**Acceptance Criteria**

- [x] Common intents and intents created by users are displayed separately in the list
- [x] It is possible to order the list of intents alphabetically, by date last modified or by whether the intent is in model
- [x] It is possible to filter out common intents so that only user created intents are visible

**Comment by ffrose** [comment]
[BUG] 
It filters Common intents with  `isCommon: intent.id.startsWith('common_'),` = if .id starts with common
How it should be:  `isCommon: intent.title.startsWith('common_'),` it should use Title, not id to filter is it common intent or not.
![Image](https://github.com/user-attachments/assets/e65dd88a-5084-4b0d-9f8f-4de9f2066de5)

When using filter any of the 2, "Viimatu muudetud" it does not work because Last Changed is always "Puudub" so it doesnt understand when a change has been made.
![Image](https://github.com/user-attachments/assets/49e24141-4f80-41ea-9813-f8ee3d4c4e3a)

**Comment by jaX10bt** [comment]
Testing blocked by https://github.com/buerokratt/Training-Module/issues/653

**Comment by jaX10bt** [comment]
Seems to work as intended
