### ISSUE TITLE
[BUG] Invalid last changed information

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Training-Module#653]
[BUG]

How it is:
As of right now intents show Last changed: Puudub/Missing
It displays the actual last changed information(Video provided) but within a second it gets replaced.
https://github.com/user-attachments/assets/38fa1c27-c373-4563-9889-bdd144b1166f

How it should be:
When changing the content of an existing intent, it updates the last changed time.

**Comment by Minwasko** [comment]
Original `Last changed` issue was fixed with the new deployment.

- https://github.com/buerokratt/Training-Module/pull/657

This PR addresses an issue where upon initial load of intents NLUs under `DSL/DMapper/locations/nlu` - `examples` field was not initialised correctly and would only appear after a new intent example was added. 

From now on with every deployment intents' examples should be displayed correctly after a new deployment right away on https://admin.test.buerokratt.ee/training/training/intents.

**Comment by ffrose** [comment]
Works as intended.
